version: '3.8'

services:
  app:
    build: .
    env_file:
      .env
    ports:
      - 5000:${port}
    volumes:
      - /app/node_modules
      - ./:/app
    restart: always

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

